from __future__ import annotations

from typing import Any, Protocol


class NFLDataProvider(Protocol):
    """Provider-neutral contract so the model is not tied to one API vendor."""

    def schedule(self, season: int, week: int | None = None) -> list[dict[str, Any]]: ...

    def game(self, game_id: str) -> dict[str, Any]: ...

    def play_by_play(self, game_id: str) -> list[dict[str, Any]]: ...

    def player_game_stats(self, game_id: str) -> list[dict[str, Any]]: ...

    def rosters(self, season: int) -> list[dict[str, Any]]: ...

    def depth_charts(self, season: int, week: int) -> list[dict[str, Any]]: ...

    def injuries(self, season: int, week: int) -> list[dict[str, Any]]: ...

    def odds(self, game_id: str) -> list[dict[str, Any]]: ...
