from __future__ import annotations

# AUTO-GENERATED by scripts/setup_ucl_slate.py
UCL_LEAGUE_ID = 2
SEASON = 2026
MATCH_DATE = '2026-09-10'

FIXTURES = {1635708: {'home': {'id': 197, 'name': 'PSV Eindhoven'},
           'away': {'id': 550, 'name': 'Shakhtar Donetsk'}},
 1635659: {'home': {'id': 611, 'name': 'Fenerbahçe'}, 'away': {'id': 497, 'name': 'AS Roma'}},
 1635697: {'home': {'id': 33, 'name': 'Manchester United'},
           'away': {'id': 13976, 'name': 'Sabah FA'}},
 1635632: {'home': {'id': 157, 'name': 'Bayern München'},
           'away': {'id': 327, 'name': 'Bodo/Glimt'}},
 1635729: {'home': {'id': 560, 'name': 'Slavia Praha'}, 'away': {'id': 116, 'name': 'Lens'}},
 1635648: {'home': {'id': 895, 'name': 'Como'}, 'away': {'id': 173, 'name': 'RB Leipzig'}}}

TEAMS = {
    team["id"]: team["name"]
    for fixture in FIXTURES.values()
    for team in (fixture["home"], fixture["away"])
}

DOMESTIC_LEAGUES = {497: {'league_id': 135, 'league_name': 'Serie A', 'country': 'Italy'},
 157: {'league_id': 78, 'league_name': 'Bundesliga', 'country': 'Germany'},
 327: {'league_id': 103, 'league_name': 'Eliteserien', 'country': 'Norway'},
 895: {'league_id': 135, 'league_name': 'Serie A', 'country': 'Italy'},
 611: {'league_id': 203, 'league_name': 'Süper Lig', 'country': 'Turkey'},
 116: {'league_id': 61, 'league_name': 'Ligue 1', 'country': 'France'},
 33: {'league_id': 39, 'league_name': 'Premier League', 'country': 'England'},
 197: {'league_id': 88, 'league_name': 'Eredivisie', 'country': 'Netherlands'},
 173: {'league_id': 78, 'league_name': 'Bundesliga', 'country': 'Germany'},
 13976: {'league_id': 419, 'league_name': 'Premyer Liqa', 'country': 'Azerbaijan'},
 550: {'league_id': 333, 'league_name': 'Premier League', 'country': 'Ukraine'},
 560: {'league_id': 345, 'league_name': 'Czech Liga', 'country': 'Czech-Republic'}}
