from __future__ import annotations

import argparse
import pprint
import sys
from datetime import date
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from ingest.api_football import APIFootballClient
from ingest.fixtures import ucl_fixtures_for_date

UCL_LEAGUE_ID = 2


def score_candidate(row: dict[str, Any]) -> tuple[int, str]:
    league = row.get("league", {})
    country = row.get("country", {})
    league_id = int(league.get("id") or 0)
    name = str(league.get("name") or "")
    league_type = str(league.get("type") or "")
    country_name = str(country.get("name") or "")

    score = 0
    if league_type.lower() == "league":
        score += 100
    if league_id == UCL_LEAGUE_ID:
        score -= 1000

    lowered = name.lower()
    for token in (
        "champions league",
        "europa",
        "conference",
        "cup",
        "super cup",
        "friendly",
        "reserve",
        "u21",
        "u19",
    ):
        if token in lowered:
            score -= 250

    # Prefer a named domestic country competition over international rows.
    if country_name and country_name.lower() not in {"world", "europe"}:
        score += 20

    return score, f"{country_name} | {name}"


def domestic_league(client: APIFootballClient, team_id: int, season: int) -> dict[str, Any]:
    rows = client.leagues(team=team_id, season=season).response
    if not rows:
        raise RuntimeError(f"No league rows returned for team {team_id}")

    ranked = sorted(rows, key=score_candidate, reverse=True)
    best = ranked[0]
    league = best.get("league", {})
    country = best.get("country", {})
    best_score, _ = score_candidate(best)

    if best_score < 100:
        print(f"WARNING: weak domestic-league match for team {team_id}:")
        for row in ranked[:6]:
            l = row.get("league", {})
            c = row.get("country", {})
            score, _ = score_candidate(row)
            print(
                f"  {l.get('id')} | {l.get('name')} | "
                f"{c.get('name')} | type={l.get('type')} | score={score}"
            )

    return {
        "league_id": int(league["id"]),
        "league_name": str(league["name"]),
        "country": str(country.get("name") or ""),
    }


def pyrepr(value: Any) -> str:
    return pprint.pformat(value, sort_dicts=False, width=100)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Discover a UCL matchday and rewrite config/ucl_2026.py for that slate."
    )
    parser.add_argument("--date", default=date.today().isoformat())
    parser.add_argument("--season", type=int, default=2026)
    args = parser.parse_args()

    client = APIFootballClient()
    rows = ucl_fixtures_for_date(client, args.date, args.season)
    if not rows:
        raise SystemExit(f"No UCL fixtures returned for {args.date}.")

    fixtures: dict[int, dict[str, Any]] = {}
    teams: dict[int, str] = {}
    print(f"UCL slate {args.date}\n")

    for row in rows:
        fixture = row["fixture"]
        home = row["teams"]["home"]
        away = row["teams"]["away"]
        fixture_id = int(fixture["id"])
        home_id = int(home["id"])
        away_id = int(away["id"])

        fixtures[fixture_id] = {
            "home": {"id": home_id, "name": str(home["name"])},
            "away": {"id": away_id, "name": str(away["name"])},
        }
        teams[home_id] = str(home["name"])
        teams[away_id] = str(away["name"])

        print(
            f"{fixture_id} | {home['name']} ({home_id}) vs "
            f"{away['name']} ({away_id}) | {fixture['date']}"
        )

    print("\nDiscovering domestic leagues...")
    domestic: dict[int, dict[str, Any]] = {}
    for team_id, team_name in sorted(teams.items(), key=lambda x: x[1]):
        info = domestic_league(client, team_id, args.season)
        domestic[team_id] = info
        print(
            f"{team_name:24s} -> {info['league_id']} | "
            f"{info['league_name']} | {info['country']}"
        )

    config = f'''from __future__ import annotations

# AUTO-GENERATED by scripts/setup_ucl_slate.py
UCL_LEAGUE_ID = {UCL_LEAGUE_ID}
SEASON = {args.season}
MATCH_DATE = {args.date!r}

FIXTURES = {pyrepr(fixtures)}

TEAMS = {{
    team["id"]: team["name"]
    for fixture in FIXTURES.values()
    for team in (fixture["home"], fixture["away"])
}}

DOMESTIC_LEAGUES = {pyrepr(domestic)}
'''

    target = ROOT / "config" / "ucl_2026.py"
    target.write_text(config, encoding="utf-8")

    print(f"\nWrote {target}")
    print(f"Fixtures: {len(fixtures)} | Teams: {len(teams)} | Domestic leagues: {len(set(x['league_id'] for x in domestic.values()))}")
    print("\nNext:")
    print("  python scripts/backfill_domestic_history.py")
    print("  python scripts/build_team_profiles.py")
    print("  python scripts/build_stat_baselines.py")
    print("  python scripts/backfill_ucl_team_history.py")
    print("  python scripts/build_stat_transfers.py")
    print("  python scripts/predict_stat_markets.py")
    print("  python scripts/audit_odds_markets.py")
    print("  python scripts/compare_stat_edges.py --top 50")


if __name__ == "__main__":
    main()
